import MovieButton from "./MovieButton";

function MovieList() {
  const director = "Andrei Tarkovsky";
  const movies = [
    {
      title: "Stalker",
      durationMin: 163,
      releaseDateMonth: "October",
      releaseDateDay: 20,
      releaseDateYear: 1982,
      director,
      cinematographers: [
        "Georgy Rerberg",
        "Alexander Knyazhinsky",
        "Leonid Kalashnikov",
      ],
      languages: ["Russian"],
      adaptedFrom: "Roadside Picnic",
      aspectRatio: "1.33:1",
      imdb: "https://www.imdb.com/title/tt0079944/",
      wikipedia: "https://en.wikipedia.org/wiki/Stalker_(1979_film)",
      rottenTomatoes: "https://www.rottentomatoes.com/m/1043378-stalker",
      rottenTomatoesScore: 100,
    },
    {
      title: "Mirror",
      durationMin: 108,
      releaseDateMonth: "January",
      releaseDateDay: 1,
      releaseDateYear: 1975,
      director,
      cinematographers: ["Georgy Rerberg"],
      languages: ["Hindi", "Spanish", "Russian", "Serbian"],
      aspectRatio: "1.37:1",
      imdb: "https://www.imdb.com/title/tt0072443/",
      imdbScore: 7.9,
      wikipedia: "https://en.wikipedia.org/wiki/Mirror_(1975_film)",
      rottenTomatoes: "https://www.rottentomatoes.com/m/the_mirror_1975",
      rottenTomatoesScore: 100,
    },
    {
      title: "Nostalgia",
      durationMin: 125,
      releaseDateMonth: "June",
      releaseDateDay: 2,
      releaseDateYear: 1983,
      director,
      cinematographers: ["Giuseppe Lanci"],
      languages: ["English", "Italian", "Russian"],
      budget: 0,
      adaptedFrom: "N/A",
      aspectRatio: "1.66:1",
      imdb: "https://www.imdb.com/title/tt0086022/",
      imdbScore: 7.9,
      wikipedia: "https://en.wikipedia.org/wiki/Nostalghia",
      rottenTomatoes: "https://www.imdb.com/title/tt0086022/",
      rottenTomatoesScore: 100,
    },
    {
      title: "Solaris",
      durationMin: 167,
      releaseDateMonth: "February",
      releaseDateDay: 5,
      releaseDateYear: 1972,
      director,
      cinematographers: ["Giuseppe Lanci"],
      languages: ["Russian", "German"],
      aspectRatio: "",
      imdb: "https://www.imdb.com/title/tt0069293/",
      imdbScore: 7.9,
      wikipedia: "https://en.wikipedia.org/wiki/Solaris_(1972_film)",
      rottenTomatoes: "https://www.rottentomatoes.com/m/solaris_1976",
      rottenTomatoesScore: 93,
    },
    {
      title: "Sacrifice",
      durationMin: 142,
      releaseDateMonth: "May",
      releaseDateDay: 9,
      releaseDateYear: 1986,
      director,
      cinematographers: ["Sven Nykvist"],
      languages: ["English", "Spanish", "French", "Turkish", "Swedish"],
      aspectRatio: "",
      imdb: "https://www.imdb.com/title/tt0091670/",
      imdbScore: 7.9,
      wikipedia: "https://en.wikipedia.org/wiki/The_Sacrifice_(1986_film)",
      rottenTomatoes: "https://www.rottentomatoes.com/m/the_sacrifice_1986",
      rottenTomatoesScore: 86,
    },
    {
      title: "Andrei Roublev",
      durationMin: 150,
      releaseDateMonth: "",
      releaseDateDay: 0,
      releaseDateYear: 1966,
      director,
      cinematographers: ["Vadim Yusov"],
      languages: ["Russian", "Spanish", "English"],
      aspectRatio: "2.35:1",
      imdb: "https://www.imdb.com/title/tt0060107/",
      imdbScore: 8.0,
      wikipedia: "https://en.wikipedia.org/wiki/Andrei_Rublev_(film)",
      rottenTomatoes: "https://www.rottentomatoes.com/m/andrei_rublev",
      rottenTomatoesScore: 96,
    },
    {
      title: "Ivan's Childhood",
      durationMin: 95,
      releaseDateMonth: "June",
      releaseDateDay: 27,
      releaseDateYear: 1963,
      director,
      cinematographers: ["Vadim Yusov"],
      languages: ["Russian"],
      aspectRatio: "1.37:1",
      imdb: "https://www.imdb.com/title/tt0056111/",
      imdbScore: 8.0,
      wikipedia: "https://en.wikipedia.org/wiki/Ivan%27s_Childhood",
      rottenTomatoes: "https://www.rottentomatoes.com/m/ivans_childhood",
      rottenTomatoesScore: 100,
    },
  ];
  return (
    <aside>
      <ul>
        {movies.map((movie, index) => (
          <MovieButton key={index} movieTitle={movie}></MovieButton>
        ))}
      </ul>
    </aside>
  );
}

export default MovieList;
